### PR TITLE
Check matmul types and error at compile-time if the backend doesn't support them

### LINKED ISSUE #538: [BUG] `matmul` do not support int32 tensors.
**Describe the bug**
It seems like the cuBLASLt-backed GEMM (`matx::matmul`) do not support `int` type, and it just **gives wrong result without complaining about unsupported types**.

**To Reproduce**
1. Write a simple GEMM example code that multiplies two int matrices:
```cpp
#include "matx.h"
#include <cassert>
#include <cstdio>

using namespace matx;

int main() {
  MATX_ENTER_HANDLER();

  index_t M = 2;
  index_t N = 3;

  auto m = make_tensor<int>({M, N});
  auto v = make_tensor<int>({N, 1});

  m.SetVals({{1, 2, 3},
             {4, 5, 6}});
  v.SetVals({{1, 2, 3}});

  auto out = make_tensor<int>({M, 1});

  (out = matmul(m, v)).run();

  cudaStreamSynchronize(0);

  printf("m:\n");
  print(m);
  printf("v:\n");
  print(v);
  printf("out:\n");
  print(out);

  CUDA_CHECK_LAST_ERROR();
  MATX_EXIT_HANDLER();
}
```
2. Build the code and run, you will get this output with all-zero result (cuBLASLt as the default backend):
```
m:
Tensor{int32_t} Rank: 2, Sizes:[2, 3], Strides:[3,1]
000000: 1 2 3 
000001: 4 5 6 
v:
Tensor{int32_t} Rank: 2, Sizes:[3, 1], Strides:[1,1]
000000: 1 
000001: 2 
000002: 3 
out:
Tensor{int32_t} Rank: 2, Sizes:[2, 1], Strides:[1,1]
000000: 0 
000001: 0
```

**Expected behavior**
The result should be `[14, 32]` like float matmul:
```
m:
Tensor{float} Rank: 2, Sizes:[2, 3], Strides:[3,1]
000000: 1.0000e+00 2.0000e+00 3.0000e+00 
000001: 4.0000e+00 5.0000e+00 6.0000e+00 
v:
Tensor{float} Rank: 2, Sizes:[3, 1], Strides:[1,1]
000000: 1.0000e+00 
000001: 2.0000e+00 
000002: 3.0000e+00 
out:
Tensor{float} Rank: 2, Sizes:[2, 1], Strides:[1,1]
000000: 1.4000e+01 
000001: 3.2000e+01
```

**Code snippers**
Listed above.

**System details (please complete the following information):**
 - OS: Ubuntu 22.04
 - CUDA version: 11.8.89
 - g++ version: 11.4.0

**Additional context**
I also tried turning on CUTLASS (`-DMATX_EN_CUTLASS=ON`) and it can support `int` tensors with some minor fixes.

Currently in MatX, the `matmul_impl()` uses cuBLASLt as the default GEMM provider and don't have a easy way to switch to CUTLASS, so I changed the template default parameter into `PROVIDER_TYPE_CUTLASS`:

```diff
template <typename TensorTypeC, typename TensorTypeA, typename TensorTypeB, 
-         MatXMatMulProvider_t PROV = PROVIDER_TYPE_CUBLASLT>
+         MatXMatMulProvider_t PROV = PROVIDER_TYPE_CUTLASS>
void matmul_impl(TensorTypeC C, const TensorTypeA A,
            const TensorTypeB B, cudaStream_t stream = 0,
            float alpha = 1.0, float beta = 0.0)
{
```

Then I changed this in `matxMatMulHandle_t::MatMulLaunch` to suppress the compiler's float-to-int conversion error:
```diff
typename CutlassGemm::Arguments args(
            {static_cast<int>(params_.m), static_cast<int>(params_.n),
             static_cast<int>(params_.k)}, // Gemm Problem dimensions
            {a.Data(),
             static_cast<int>(params_.lda)}, // Tensor-ref for source matrix A
            {b.Data(),
             static_cast<int>(params_.ldb)}, // Tensor-ref for source matrix B
            {c.Data(),
             static_cast<int>(params_.ldc)}, // Tensor-ref for source matrix C
            {c.Data(),
             static_cast<int>(
                 params_.ldc)}, // Tensor-ref for destination matrix D (may be
                                // different memory than source C matrix)
-           {alpha, beta});     // Scalars used in the Epilogue
+           {static_cast<T1>(alpha), static_cast<T1>(beta)});     // Scalars used in the Epilogue
```

Now the output is normal:

```
m:
Tensor{int32_t} Rank: 2, Sizes:[2, 3], Strides:[3,1]
000000: 1 2 3 
000001: 4 5 6 
v:
Tensor{int32_t} Rank: 2, Sizes:[3, 1], Strides:[1,1]
000000: 1 
000001: 2 
000002: 3 
out:
Tensor{int32_t} Rank: 2, Sizes:[2, 1], Strides:[1,1]
000000: 14 
000001: 32
```

**My suggestion**
If it is not necessary to support int32 GEMM, we can throw an error to the user that it is not supported, and tell him/her to either use the CUTLASS's version or use float32 as the solution.

### PR DESCRIPTION
**Pull request by cliffburdick**
Fixes #538

### CODE REVIEW

**Comment by AtomicVar** [comment]
@cliffburdick Great work! But I wonder why `int8_t` is listed as supported GEMM types? I tried `int8_t` GEMM and it failed. `cublasLtMatmulAlgoGetHeuristic()` in `ConfigureCublasLt()` will return a `CUBLAS_STATUS_NOT_SUPPORTED` if we use `int8_t`.

Code to reproduce:

```cpp
#include "matx.h"
#include <cassert>
#include <cstdio>

using namespace matx;

#define TYPE int8_t

int main() {
  MATX_ENTER_HANDLER();

  index_t M = 2;
  index_t N = 3;

  auto m = make_tensor<TYPE>({M, N});
  auto v = make_tensor<TYPE>({N, 1});

  m.SetVals({{1, 2, 3},
             {4, 5, 6}});
  v.SetVals({{1, 2, 3}});

  auto out = make_tensor<TYPE>({M, 1});

  (out = matmul(m, v)).run();

  cudaStreamSynchronize(0);

  printf("m:\n");
  print(m);
  printf("v:\n");
  print(v);
  printf("out:\n");
  print(out);

  CUDA_CHECK_LAST_ERROR();
  MATX_EXIT_HANDLER();
}
```

Output:
```
matxException (matxMatMulError: ret == CUBLAS_STATUS_SUCCESS) - /workspaces/MatX/include/matx/transforms/matmul.h:714

Stack Trace:
 examples/matmul_int : ()+0x8e4d
 examples/matmul_int : ()+0x1a3ee
 examples/matmul_int : ()+0x17ff0
 examples/matmul_int : ()+0x143f5
 examples/matmul_int : ()+0x10e16
 examples/matmul_int : ()+0x6664
 /lib/x86_64-linux-gnu/libc.so.6 : ()+0x29d90
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0x80
 examples/matmul_int : ()+0x4ea5
```

**Comment by cliffburdick** [comment]
> @cliffburdick Great work! But I wonder why `int8_t` is listed as a supported GEMM type? I tried `int8_t` GEMM and it failed. `cublasLtMatmulAlgoGetHeuristic()` in `ConfigureCublasLt()` will return a `CUBLAS_STATUS_NOT_SUPPORTED` if we use `int8_t`.
> 
> Code to reproduce:
> 
> ```c++
> #include "matx.h"
> #include <cassert>
> #include <cstdio>
> 
> using namespace matx;
> 
> #define TYPE int8_t
> 
> int main() {
>   MATX_ENTER_HANDLER();
> 
>   index_t M = 2;
>   index_t N = 3;
> 
>   auto m = make_tensor<TYPE>({M, N});
>   auto v = make_tensor<TYPE>({N, 1});
> 
>   m.SetVals({{1, 2, 3},
>              {4, 5, 6}});
>   v.SetVals({{1, 2, 3}});
> 
>   auto out = make_tensor<TYPE>({M, 1});
> 
>   (out = matmul(m, v)).run();
> 
>   cudaStreamSynchronize(0);
> 
>   printf("m:\n");
>   print(m);
>   printf("v:\n");
>   print(v);
>   printf("out:\n");
>   print(out);
> 
>   CUDA_CHECK_LAST_ERROR();
>   MATX_EXIT_HANDLER();
> }
> ```
> 
> Output:
> 
> ```
> matxException (matxMatMulError: ret == CUBLAS_STATUS_SUCCESS) - /workspaces/MatX/include/matx/transforms/matmul.h:714
> 
> Stack Trace:
>  examples/matmul_int : ()+0x8e4d
>  examples/matmul_int : ()+0x1a3ee
>  examples/matmul_int : ()+0x17ff0
>  examples/matmul_int : ()+0x143f5
>  examples/matmul_int : ()+0x10e16
>  examples/matmul_int : ()+0x6664
>  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x29d90
>  /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0x80
>  examples/matmul_int : ()+0x4ea5
> ```

I'm going by the support matrix here:
https://docs.nvidia.com/cuda/cublas/#id98

I will try it out

**Comment by cliffburdick** [comment]
@AtomicVar the reason it's not working is the compute and scale types are wrong. Looking into it.

**Comment by cliffburdick** [comment]
> @AtomicVar the reason it's not working is the compute and scale types are wrong. Looking into it.

Even with the correct scalar and compute types it's failing the heuristic check. Still investigating

**Comment by AtomicVar** [comment]
> Even with the correct scalar and compute types it's failing the heuristic check. Still investigating

I'm also facing this weird issue. Don't know where's the problem.

**Review by tbensonatl — APPROVED** [review]

**Pull request merged**
