### PR TITLE
New rapids and nvbench

### PR DESCRIPTION
**Pull request by cliffburdick**

### CODE REVIEW

**Review by tylera-nvidia — APPROVED** [review]

**Comment by tylera-nvidia** [comment]
One thing I noticed is that the docs currently don't have a version # in it for our third-party requirements here: https://nvidia.github.io/MatX/build.html#required-third-party-dependencies

For some customers we may want to list the most-recent versions, as they will need to get those approved to their labs.

also is [libcudacxx](https://github.com/NVIDIA/libcudacxx) still the correct requirement, or should it be updated to CCCL?

**Comment by cliffburdick** [comment]
> One thing I noticed is that the docs currently don't have a version # in it for our third-party requirements here: https://nvidia.github.io/MatX/build.html#required-third-party-dependencies
> 
> For some customers we may want to list the currently used versions, as they will need to get those approved to their labs.
> 
> also is [libcudacxx](https://github.com/NVIDIA/libcudacxx) still the correct requirement, or should it be updated to CCCL?

These are all resolved in the latest commit

**Pull request merged**
