### PR TITLE
Fix use of deprecated constructor.

### PR DESCRIPTION
**Pull request by pkestene**
Make sure example spectrogram_graph builds fine under flag `-Werror`

### CODE REVIEW

**Comment by cliffburdick** [comment]
Hi @pkestene , thanks for the report. Can you please let us know the compiler you're using and error you see? The code there should be valid; `make_tensor` can take any shape meeting the iterator criteria, and std::array is one of them. I'm compiling here with `-Werror` and don't see the issue you're seeing.

**Comment by pkestene** [comment]
Hi @cliffburdick 

strangely, I can't reproduce the error I was seeing yesterday (?), sorry about that.

Nevertheless, I do can see an error when swithing build type between release and debug:

I'm working on ubuntu 22.04, defaut compiler is g++ (11.2).

1. when compiling in debug, everything is ok:
- `cmake -DCMAKE_BUILD_TYPE=Debug -DMATX_BUILD_EXAMPLES=ON ..; make` => no error.

2. when compiling in release, I get the following error when building example recursive_filter:
- `cmake -DCMAKE_BUILD_TYPE=Release -DMATX_BUILD_EXAMPLES=ON ..; make VERBOSE=1`

```text
[ 16%] Building CUDA object examples/CMakeFiles/recursive_filter.dir/recursive_filter.cu.o
cd /data/pkestene/install/nvidia/MatX/git/MatX/build/examples && /usr/local/cuda-11.7/bin/nvcc -forward-unknown-to-host-compiler -DINDEX_64_BIT -DMATX_ENABLE_CUTENSOR=0 -DMATX_ENABLE_CUTLASS=0 -DMATX_ENABLE_FILEIO=1 -DMATX_ENABLE_PYBIND11=1 -DMATX_ENABLE_VIZ=0 -I/data/pkestene/install/nvidia/MatX/git/MatX/include -I/data/pkestene/install/nvidia/MatX/git/MatX/include/kernels -I/data/pkestene/install/nvidia/MatX/git/MatX/include/common -isystem=/data/pkestene/install/nvidia/MatX/git/MatX/build/_deps/pybind11-src/include -isystem=/usr/include/python3.10 -isystem=/usr/local/cuda-11.7/include -arch=sm_75 -O3 -DNDEBUG --generate-code=arch=compute_75,code=[sm_75] -Wall -Wextra -Werror all-warnings -Wcast-align -Wunused -Wconversion -Wno-unknown-pragmas -Wnon-virtual-dtor -Wshadow -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -arch=sm_75 --threads 0 --expt-relaxed-constexpr -isystem=/usr/local/cuda-11.7/include -DMATX_ROOT=\"/data/pkestene/install/nvidia/MatX/git/MatX\" -fvisibility=hidden -MD -MT examples/CMakeFiles/recursive_filter.dir/recursive_filter.cu.o -MF CMakeFiles/recursive_filter.dir/recursive_filter.cu.o.d -x cu -c /data/pkestene/install/nvidia/MatX/git/MatX/examples/recursive_filter.cu -o CMakeFiles/recursive_filter.dir/recursive_filter.cu.o
/data/pkestene/install/nvidia/MatX/git/MatX/include/matx/core/storage.h: In function ‘void matx::filter(OutType&, const InType&, std::array<FilterType, NR>, std::array<FilterType, NNR>, cudaStream_t) [with long unsigned int NR = 2; long unsigned int NNR = 2; OutType = matx::tensor_t<float, 2>; InType = matx::tensor_t<float, 2>; FilterType = float]’:
/data/pkestene/install/nvidia/MatX/git/MatX/include/matx/core/storage.h:81:1: error: ‘nonrec_v.matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >, matx::tensor_desc_t<std::array<long long int, 1>, std::array<long long int, 1>, 1> >::storage_.matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >::container_.matx::raw_pointer_buffer<float, matx::matx_allocator<float> >::owning_’ may be used uninitialized [-Werror=maybe-uninitialized]
   81 |      raw_pointer_buffer(const raw_pointer_buffer &rhs) = default;
      | ^    ~~~~~~~~~~~~~
/data/pkestene/install/nvidia/MatX/git/MatX/include/matx/transforms/filter.h:431:27: note: ‘nonrec_v.matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >, matx::tensor_desc_t<std::array<long long int, 1>, std::array<long long int, 1>, 1> >::storage_.matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >::container_.matx::raw_pointer_buffer<float, matx::matx_allocator<float> >::owning_’ was declared here
  431 |   tensor_t<FilterType, 1> nonrec_v({static_cast<index_t>(h_nonrec.size())});
      |                           ^~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [examples/CMakeFiles/recursive_filter.dir/build.make:76: examples/CMakeFiles/recursive_filter.dir/recursive_filter.cu.o] Error 255
make[2]: Leaving directory '/data/pkestene/install/nvidia/MatX/git/MatX/build'
make[1]: *** [CMakeFiles/Makefile2:176: examples/CMakeFiles/recursive_filter.dir/all] Error 2
make[1]: Leaving directory '/data/pkestene/install/nvidia/MatX/git/MatX/build'

```

**Comment by cliffburdick** [comment]
thanks @pkestene! let us look into it and get back to you

**Comment by cliffburdick** [comment]
> Hi @cliffburdick
> 
> strangely, I can't reproduce the error I was seeing yesterday (?), sorry about that.
> 
> Nevertheless, I do can see an error when swithing build type between release and debug:
> 
> I'm working on ubuntu 22.04, defaut compiler is g++ (11.2).
> 
> 1. when compiling in debug, everything is ok:
> 
> * `cmake -DCMAKE_BUILD_TYPE=Debug -DMATX_BUILD_EXAMPLES=ON ..; make` => no error.
> 
> 2. when compiling in release, I get the following error when building example recursive_filter:
> 
> * `cmake -DCMAKE_BUILD_TYPE=Release -DMATX_BUILD_EXAMPLES=ON ..; make VERBOSE=1`
> 
> ```
> [ 16%] Building CUDA object examples/CMakeFiles/recursive_filter.dir/recursive_filter.cu.o
> cd /data/pkestene/install/nvidia/MatX/git/MatX/build/examples && /usr/local/cuda-11.7/bin/nvcc -forward-unknown-to-host-compiler -DINDEX_64_BIT -DMATX_ENABLE_CUTENSOR=0 -DMATX_ENABLE_CUTLASS=0 -DMATX_ENABLE_FILEIO=1 -DMATX_ENABLE_PYBIND11=1 -DMATX_ENABLE_VIZ=0 -I/data/pkestene/install/nvidia/MatX/git/MatX/include -I/data/pkestene/install/nvidia/MatX/git/MatX/include/kernels -I/data/pkestene/install/nvidia/MatX/git/MatX/include/common -isystem=/data/pkestene/install/nvidia/MatX/git/MatX/build/_deps/pybind11-src/include -isystem=/usr/include/python3.10 -isystem=/usr/local/cuda-11.7/include -arch=sm_75 -O3 -DNDEBUG --generate-code=arch=compute_75,code=[sm_75] -Wall -Wextra -Werror all-warnings -Wcast-align -Wunused -Wconversion -Wno-unknown-pragmas -Wnon-virtual-dtor -Wshadow -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -arch=sm_75 --threads 0 --expt-relaxed-constexpr -isystem=/usr/local/cuda-11.7/include -DMATX_ROOT=\"/data/pkestene/install/nvidia/MatX/git/MatX\" -fvisibility=hidden -MD -MT examples/CMakeFiles/recursive_filter.dir/recursive_filter.cu.o -MF CMakeFiles/recursive_filter.dir/recursive_filter.cu.o.d -x cu -c /data/pkestene/install/nvidia/MatX/git/MatX/examples/recursive_filter.cu -o CMakeFiles/recursive_filter.dir/recursive_filter.cu.o
> /data/pkestene/install/nvidia/MatX/git/MatX/include/matx/core/storage.h: In function ‘void matx::filter(OutType&, const InType&, std::array<FilterType, NR>, std::array<FilterType, NNR>, cudaStream_t) [with long unsigned int NR = 2; long unsigned int NNR = 2; OutType = matx::tensor_t<float, 2>; InType = matx::tensor_t<float, 2>; FilterType = float]’:
> /data/pkestene/install/nvidia/MatX/git/MatX/include/matx/core/storage.h:81:1: error: ‘nonrec_v.matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >, matx::tensor_desc_t<std::array<long long int, 1>, std::array<long long int, 1>, 1> >::storage_.matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >::container_.matx::raw_pointer_buffer<float, matx::matx_allocator<float> >::owning_’ may be used uninitialized [-Werror=maybe-uninitialized]
>    81 |      raw_pointer_buffer(const raw_pointer_buffer &rhs) = default;
>       | ^    ~~~~~~~~~~~~~
> /data/pkestene/install/nvidia/MatX/git/MatX/include/matx/transforms/filter.h:431:27: note: ‘nonrec_v.matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >, matx::tensor_desc_t<std::array<long long int, 1>, std::array<long long int, 1>, 1> >::storage_.matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >::container_.matx::raw_pointer_buffer<float, matx::matx_allocator<float> >::owning_’ was declared here
>   431 |   tensor_t<FilterType, 1> nonrec_v({static_cast<index_t>(h_nonrec.size())});
>       |                           ^~~~~~~~
> cc1plus: all warnings being treated as errors
> make[2]: *** [examples/CMakeFiles/recursive_filter.dir/build.make:76: examples/CMakeFiles/recursive_filter.dir/recursive_filter.cu.o] Error 255
> make[2]: Leaving directory '/data/pkestene/install/nvidia/MatX/git/MatX/build'
> make[1]: *** [CMakeFiles/Makefile2:176: examples/CMakeFiles/recursive_filter.dir/all] Error 2
> make[1]: Leaving directory '/data/pkestene/install/nvidia/MatX/git/MatX/build'
> ```

Hi @pkestene all of these issues are fixed for release mode and the unit tests pass. Please give it another chance and let us know if it works. Thanks.

**Comment by pkestene** [comment]
@luitjens yes everything fine now. Thank you.

**Pull request closed without merging**
