### PR TITLE
Automatically publish docs to GH Pages on merge to main

### PR DESCRIPTION
**Pull request by tmartin-gh**
This change will build the MatX docs when a PR is merged to main.

### CODE REVIEW

**Review by cliffburdick — APPROVED** [review]
What happens if building the docs fails? are we notified?

**Comment by tmartin-gh** [comment]
Standard Github notification events go out - e.g. to your email.  Search for subject line "[NVIDIA/MatX] Run failed: Build Docs and deploy to Github Pages"

**Comment by tmartin-gh** [comment]
> Standard Github notification events go out on a failure - e.g. to your email. Search for subject line "[NVIDIA/MatX] Run failed: Build Docs and deploy to Github Pages"



> What happens if building the docs fails? are we notified?

Standard Github notification events go out on a failure - e.g. to your email. Search for subject line "[NVIDIA/MatX] Run failed: Build Docs and deploy to Github Pages"

**Comment by cliffburdick** [comment]
> > What happens if building the docs fails? are we notified?
> 
> Standard Github notification events go out on a failure - e.g. to your email. Search for subject line "[NVIDIA/MatX] Run failed: Build Docs and deploy to Github Pages"

Will it prevent the MR from merging?

**Pull request merged**
