### PR TITLE
Generator Printing Patch

### PR DESCRIPTION
**Pull request by tylera-nvidia**
Fix to support correct specialization for generator printing (switched order of Print Utility and PrintData function). Also added cast to protect from warnings for conflicting size/stride sizes

### CODE REVIEW

**Review by cliffburdick — APPROVED** [review]

**Comment by tylera-nvidia** [comment]
`[----------] Global test environment tear-down
[==========] 1263 tests from 353 test suites ran. (675302 ms total)
[  PASSED  ] 1263 tests.

  YOU HAVE 20 DISABLED TESTS

docker@ipp1-1946:/home/tallen/scratch/playground/matxExample/MatX/build$ git status
On branch generatorPrintPatch
Your branch is up to date with 'origin/generatorPrintPatch'.

nothing to commit, working tree clean
docker@ipp1-1946:/home/tallen/scratch/playground/matxExample/MatX/build$  git rev-parse HEAD
63822018f5b0341e0a643cfc1ada78daf93c40e8
docker@ipp1-1946:/home/tallen/scratch/playground/matxExample/MatX/build$ `

**Comment by luitjens** [comment]
@tylera-nvidia can you rebase.  it looks like we have conflicts.

**Review by cliffburdick — APPROVED** [review]

**Comment by tylera-nvidia** [comment]
[----------] Global test environment tear-down
[==========] 1282 tests from 353 test suites ran. (684566 ms total)
[  PASSED  ] 1282 tests.

  YOU HAVE 20 DISABLED TESTS

docker@ipp1-1946:/home/tallen/scratch/MatX/build$ git status
On branch generatorPrintPatch
Your branch is up to date with 'origin/generatorPrintPatch'.

nothing to commit, working tree clean
docker@ipp1-1946:/home/tallen/scratch/MatX/build$ git rev-parse HEAD
fc0d90ed5c0d04f64bf842f48c196981f4eefe0a

**Pull request merged**
